Fix session manager tests

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -27,54 +27,46 @@ jobs:
       with:
         go-version: 1.14.x
 
-    # - name: Ensure tidy gomod
-    #   run: |
-    #     make vendor
-    #     if ! git diff --exit-code
-    #     then
-    #       echo "go mod not tidy"
-    #       exit 1
-    #     fi
+    - name: Ensure tidy gomod
+      run: |
+        make vendor
+        if ! git diff --exit-code
+        then
+          echo "go mod not tidy"
+          exit 1
+        fi
 
     - name: Lint
       run: |
         make lint.all
 
-  # unit-tests:
-  #   needs:
-  #   - stylecheck
-  #   strategy:
-  #     matrix:
-  #       go-version:
-  #       - 1.14.x
-  #       # - 1.15.x
-  #       os:
-  #       - ubuntu-latest
-  #       # - windows-latest
-  #   runs-on: ${{ matrix.os }}
-  #   steps:
-  #   - uses: actions/setup-go@v2
-  #     with:
-  #       go-version: ${{ matrix.go-version }}
-  #   - uses: actions/checkout@v2
-  #   - name: Test Packages
-  #     run: |
-  #       make test.pkg
+  unit-tests:
+    needs:
+    - stylecheck
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/setup-go@v2
+      with:
+        go-version: 1.14.x
+    - uses: actions/checkout@v2
+    - name: Test Packages
+      run: |
+        make test.pkg
 
-  #   - name: Test Commands
-  #     run: |
-  #       make test.cmd
+    - name: Test Commands
+      run: |
+        make test.cmd
 
-  #   - name: Report Test Coverage
-  #     uses: codecov/codecov-action@v1
-  #     # with:
-  #     #   token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
-  #     #   fail_ci_if_error: true # optional (default = false)
+    - name: Report Test Coverage
+      uses: codecov/codecov-action@v1
+      # with:
+      #   token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
+      #   fail_ci_if_error: true # optional (default = false)
 
   build-linux-images:
     needs:
     - stylecheck
-    # - unit-tests
+    - unit-tests
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
